version: '3.8'
services:
    db:
        image: mysql:8.0.17
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    graphdb:
        #image: lyrasis/blazegraph
        #ports:
        #    - "9999:8080"
        image: nawer/blazegraph
        environment:
            JAVA_XMS: 512m
            JAVA_XMX: 1g
        volumes:
            - ./blazegraph/data:/var/lib/blazegraph
            - ./blazegraph/config:/docker-entrypoint-initdb.d
        ports:
            - "9999:9999"

    mediawiki:
        build: 
            context: ./container
            dockerfile: Dockerfile
            args:
               SSH_PASS: ${SSH_PASS}
        restart: always
        depends_on:
            - db
            - elasticsearch
            - memcached
        #    - parsoid
        #networks:
        #    - default
        #    - inter_docker
        ports:
            - "8081:80"
            - "${HOST_SSH_PORT}:22"
 
        environment:
            - MW_SITE_SERVER=${MW_SITE_SERVER}
            - MW_SITE_NAME=${MW_SITE_NAME}
            - MW_SITE_LANG=${MW_SITE_LANG}
            - MW_DEFAULT_SKIN=vector
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=${MW_ADMIN_PASS}
            - MW_DB_NAME=mediawiki
            - MW_DB_USER=mwuser
            - MW_DB_PASS=${MW_DB_PASS}
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=${MYSQL_ROOT_PASSWORD}
            - MW_AUTOUPDATE=true
            - MW_MAIN_CACHE_TYPE=CACHE_MEMCACHED
            - MW_MEMCACHED_SERVERS=memcached:11211
            - MW_SEARCH_TYPE=CirrusSearch
            - MW_CIRRUS_SEARCH_SERVERS=elasticsearch
            - MW_REST_DOMAIN=mediawiki
     #       - MW_REST_PARSOID_URL=http://parsoid:8000
            - MW_FLOW_NAMESPACES=NS_TALK,NS_USER_TALK
            - PHP_LOG_ERRORS=On
            - PHP_ERROR_REPORTING=E_ALL #Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT

    memcached:
        image: memcached
        restart: always

    elasticsearch:
        image: elasticsearch:6.5.4
        restart: always
        environment:
           - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
           - "discovery.type=single-node"

    #parsoid:
    #    image: thenets/parsoid:0.10
    #    restart: always
    #    environment:
    #        - PARSOID_NUM_WORKERS=0
    #        - PARSOID_DOMAIN_web=http://mediawiki/w/api.php

    #pdf:
    #    image: msokk/electron-render-service
    #    restart: always
    #    environment:
    #        RENDERER_ACCESS_KEY: secret

#for internal connections, e. g. non public dockered email server
#networks:
#    default:
#
#    inter_docker:
#        external:
#            name: mail_network
