name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    #- name: Build the Docker image
    #  run: docker build mediawiki/config/ --tag osl-dev:$(date +%s)
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.HUB_DOCKER_COM_SIMONTAURUS_USERNAME }}
        password: ${{ secrets.HUB_DOCKER_COM_SIMONTAURUS_PASSWORD }}
      
    #- name: Extract metadata (tags, labels) for Docker
    #  id: meta
    #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #  with:
    #    images: simontaurus/osl-mw-dev
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: mediawiki/build/
        push: true
        #tags: ${{ steps.meta.outputs.tags }}
        #labels: ${{ steps.meta.outputs.labels }}
        tags: simontaurus/osl-mw-dev:latest
